if __name__ == "__main__":
    # Mixed sample texts
    sample_texts = [
        "1. I love coding, it's amazing!",
        "2. Absolutely fantastic experience!",
        "3. Oh look, the ‘skip ad’ button appears just as the ad is about to end. How convenient!",
        "4. The food was absolutely terrible.",
        "5. I received an unexpected compliment, made my day!",
        "6. Oh joy, my favorite app just updated and now nothing works like it used to.",
        "7. I feel okay about this situation.",
        "8. My heart is filled with love and happiness!",
        "9. Oh joy, another software update that changes everything for no reason.",
        "10. I wish I never had to deal with this again.",
        "11. This book changed my perspective on life!",
        "12. The Wi-Fi is down again, just when I needed it the most.",
        "13. The sunset was breathtaking, what a sight!",
        "14. Nothing beats spending time with family and friends!",
        "15. Because nothing makes a Monday morning better than spilling coffee on my shirt.",
        "16. The test results were as expected.",
        "17. This article was informative but nothing groundbreaking.",
        "18. Oh look, my laptop battery is at 5% and my charger is conveniently in another room.",
        "19. I regret ever doing this.",
        "20. This app is so intuitive and easy to use!",
        "21. Oh fantastic, another meeting at 7 AM.",
        "22. Today was one of the best days of my life!",
        "23. I’m feeling super productive today!",
        "24. Oh wonderful, another lecture on things I already know.",
        "25. I successfully finished my project ahead of schedule!",
        "26. Oh sure, let’s all pretend like deadlines don’t exist!",
        "27. What a beautiful time for my car to run out of fuel—right in the middle of nowhere.",
        "28. I hate bugs, they ruin everything.",
        "29. I failed the test even after studying so hard.",
        "30. The restaurant had the best food ever!",
        "31. The meeting was pointless, what a waste of time.",
        "32. The weather is fine today.",
        "33. Oh joy, another power cut during my favorite show!",
        "34. This project turned out way better than expected!",
        "35. Oh yes, because everyone loves getting ignored.",
        "36. My flight got delayed again, this is frustrating.",
        "37. Oh great, another bug to fix!",
        "38. I just got a rejection email, this sucks.",
        "39. Oh great, my Wi-Fi disconnected right before I submitted my assignment.",
        "40. My pet just did something adorable again!",
        "41. Because nothing makes traffic more enjoyable than the guy who cuts in last minute.",
        "42. The kindness of strangers always restores my faith in humanity.",
        "43. I watched a movie yesterday, it was alright.",
        "44. The commute today was the same as every day.",
        "45. My favorite artist just released a new song!",
        "46. Oh perfect, another deadline moved up!",
        "47. Oh great, my headphones tangled themselves while sitting perfectly still in my bag.",
        "48. My favorite show got canceled, I’m so upset.",
        "49. Yes, please explain the joke to me. I totally didn’t get it the first time.",
        "50. Life is beautiful and full of joy!",
        "51. This is hands down the worst customer service I’ve ever experienced.",
        "52. The book was neither good nor bad.",
        "53. Oh wow, another traffic jam, just what I needed!",
        "54. This new policy makes everything so complicated.",
        "55. I dropped my phone and now the screen is shattered.",
        "56. The store had everything I needed, nothing more, nothing less.",
        "57. The concert was an unforgettable experience!",
        "58. Best decision I have ever made!",
        "59. Oh yeah, because standing in line for hours is so much fun!",
        "60. I neither liked nor disliked the movie.",
        "61. I just got promoted, I’m so happy!",
        "62. This is a regular sentence with no bias.",
        "63. The presentation went as planned.",
        "64. Oh joy, another traffic jam during rush hour!",
        "65. This book changed my perspective on life!",
        "66. The meeting ended on time, nothing unusual.",
        "67. Oh yeah, because I totally wanted my coffee spilled on me.",
        "68. The restaurant had the best food ever!",
        "69. Oh sure, because I totally wanted my phone battery to die.",
        "70. I am extremely disappointed with this.",
        "71. What a fantastic time for my phone alarm to decide not to go off!",
        "72. Meh, it's just fine.",
        "73. I got a perfect score on my exam, so proud of myself!",
        "74. The food was okay, not great but not terrible.",
        "75. This new update made this game even better!",
        "76. Oh wow, another delay at the airport, how surprising!",
        "77. Finally accomplished my goal—what a great feeling!",
        "78. I have so much work and no energy to do it.",
        "79. Waking up feeling refreshed is the best feeling ever!",
        "80. I’m feeling incredibly motivated today!",
        "81. Oh sure, because that worked so well last time.",
        "82. Absolutely fantastic experience!",
        "83. I just completed my daily routine as usual.",
        "84. Oh fantastic, another mandatory meeting.",
        "85. I received an unexpected compliment, made my day!",
        "86. I’m so grateful for all the opportunities in my life!",
        "87. Oh look, another software update that changes everything for no reason.",
        "88. Yes, I’d love to hear about your vacation while I sit here drowning in work!",
        "89. This is the worst thing ever.",
        "90. The new season of my favorite show is amazing!",
        "91. This was a standard customer service experience.",
        "92. Because nothing says ‘good morning’ like stepping on a Lego.",
        "93. The Wi-Fi is down again, just when I needed it the most.",
        "94. Oh sure, because I love getting ignored.",
        "95. I regret ever doing this.",
        "96. Oh joy, another power cut during my favorite show!",
        "97. This article was informative but nothing groundbreaking.",
        "98. I had an amazing time catching up with old friends!",
        "99. My heart is filled with love and happiness!",
        "100. Oh yes, because waiting in line for hours is so much fun!",
    ]

    analyzer = SentimentAnalyzer()

    # Analyze each text and display results
    for text in sample_texts:
        result = analyzer.analyze(text)
        print(f"Text: {text}\nSentiment: {result['sentiment']}\nScores: {result}\n")
